[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Ville Orkas <ville@orkas.fi>"]
edition = "2018"

[lib]
path = "src/rs/mandelbrot.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
num-traits = "*"
console_error_panic_hook = "*"
