[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Ville Orkas <ville@orkas.fi>"]

[lib]
path = "src/rs/mandelbrot.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
num-traits = "0.1.41"